__include__: 'darts_cifar.yaml' # defaults are loaded from this file

# common:
#   experiment_name: 'petridish_run2_seed42_eval'

search:
    alpha_optimizer:
        type: "custom"
        lr: 7.5e-4