__include__: 'darts_cifar.yaml' # defaults are loaded from this file

# XNAS's parameters 
search:
    loader: 
        train_batch: 96
    trainer:
        grad_clip: 1.0
        optimizer:
            type: "sgd"
            lr: 0.025
            decay: 0.0
            momentum: 0.0
            nesterov: False
            warmup: null
        alpha_optimizer:
            type: "custom"
            lr: 0.025
                
        
        